FROM node:22-bookworm-slim

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

RUN corepack enable

WORKDIR /app

COPY . .

RUN pnpm install --frozen-lockfile
RUN chmod +x apps/docs/start.sh

EXPOSE 3001

CMD ["./apps/docs/start.sh"]
