import { Injectable, Logger, Optional } from "@nestjs/common";
import type {
  AppLanguage,
  AnswerCitation,
  AnswerQueryResponse,
  SemanticSearchResult,
} from "@openkeep/types";

import { AppConfigService } from "../common/config/app-config.service";
import type { AnswerProvider } from "./provider.types";
import { ExtractiveAnswerProvider } from "./extractive-answer.provider";
import { LlmService, type LlmStreamChunk } from "./llm.service";
import {
  DEFAULT_ANSWER_MIN_CHUNK_SCORE,
  LOW_CONFIDENCE_MARGIN,
  LOW_CONFIDENCE_TOP_N,
  buildInsufficientEvidenceMessage,
} from "./relevance.constants";

@Injectable()
export class LlmAnswerProvider implements AnswerProvider {
  private readonly logger = new Logger(LlmAnswerProvider.name);

  constructor(
    private readonly llmService: LlmService,
    private readonly extractiveProvider: ExtractiveAnswerProvider,
    @Optional() private readonly configService?: AppConfigService,
  ) {}

  async answer(input: {
    question: string;
    results: SemanticSearchResult[];
    maxCitations: number;
    responseLanguage?: AppLanguage | null;
    signal?: AbortSignal;
  }): Promise<{
    status: AnswerQueryResponse["status"];
    answer: string | null;
    reasoning: string | null;
    citations: AnswerCitation[];
  }> {
    if (!this.llmService.isConfigured()) {
      return this.extractiveProvider.answer(input);
    }

    const context = this.buildContext(input.results);

    if (context.citations.length === 0) {
      this.logger.warn("No chunks passed score threshold — all results filtered out");
      return {
        status: "insufficient_evidence",
        answer: buildInsufficientEvidenceMessage(input.responseLanguage),
        reasoning: "No document chunks with sufficient relevance were found.",
        citations: [],
      };
    }

    const messages = this.buildMessages(input.question, context.prompt, input.responseLanguage);
    const completion = await this.llmService.completeWithFallback({
      messages,
      temperature: 0.1,
      maxTokens: 1024,
      signal: input.signal,
    });

    if (!completion.text) {
      this.logger.warn("LLM completion returned null, falling back to extractive");
      return this.extractiveProvider.answer(input);
    }

    return {
      status: "answered",
      answer: completion.text.trim(),
      reasoning: `Generated by ${completion.provider ?? "LLM"} based on ${context.citations.length} grounded excerpt(s)${context.lowConfidence ? " with low retrieval confidence" : ""}.`,
      citations: context.citations.slice(0, input.maxCitations),
    };
  }

  async *streamAnswer(input: {
    question: string;
    results: SemanticSearchResult[];
    maxCitations: number;
    responseLanguage?: AppLanguage | null;
    signal?: AbortSignal;
  }): AsyncGenerator<
    LlmStreamChunk & {
      citations?: AnswerCitation[];
      status?: AnswerQueryResponse["status"];
      lowConfidence?: boolean;
    }
  > {
    if (!this.llmService.isConfigured()) {
      const result = await this.extractiveProvider.answer(input);
      yield {
        text: result.answer ?? buildInsufficientEvidenceMessage(input.responseLanguage),
        done: false,
      };
      yield { text: "", done: true, citations: result.citations, status: result.status };
      return;
    }

    const context = this.buildContext(input.results);

    if (context.citations.length === 0) {
      this.logger.warn("No chunks passed score threshold for streaming — all results filtered out");
      yield { text: buildInsufficientEvidenceMessage(input.responseLanguage), done: false };
      yield { text: "", done: true, citations: [], status: "insufficient_evidence" };
      return;
    }

    const messages = this.buildMessages(input.question, context.prompt, input.responseLanguage);

    const stream = this.llmService.streamWithFallback({
      messages,
      temperature: 0.1,
      maxTokens: 1024,
      signal: input.signal,
    });

    // A provider can complete "successfully" without emitting a single token
    // (e.g. Gemini returning no candidate parts) — that must not surface as an
    // answered response with a null answer.
    let emittedText = false;

    for await (const chunk of stream) {
      if (chunk.done) {
        if (chunk.error) {
          yield { text: "", done: true, error: chunk.error, citations: [] };
          return;
        }
        yield {
          text: "",
          done: true,
          citations: emittedText ? context.citations.slice(0, input.maxCitations) : [],
          status: emittedText ? "answered" : "insufficient_evidence",
          lowConfidence: context.lowConfidence,
        };
        return;
      }

      if (chunk.text.length > 0) {
        emittedText = true;
      }
      yield { text: chunk.text, done: false };
    }

    yield {
      text: "",
      done: true,
      citations: emittedText ? context.citations.slice(0, input.maxCitations) : [],
      status: emittedText ? "answered" : "insufficient_evidence",
      lowConfidence: context.lowConfidence,
    };
  }

  // ---------------------------------------------------------------------------
  // Internals
  // ---------------------------------------------------------------------------

  private buildContext(results: SemanticSearchResult[]): {
    prompt: string;
    citations: AnswerCitation[];
    lowConfidence: boolean;
  } {
    const minScore =
      this.configService?.get("ANSWER_MIN_CHUNK_SCORE") ?? DEFAULT_ANSWER_MIN_CHUNK_SCORE;

    // Collect all chunks across all results with their parent document info
    const allChunks: Array<{
      chunk: SemanticSearchResult["matchedChunks"][number];
      document: SemanticSearchResult["document"];
    }> = [];

    for (const result of results) {
      for (const chunk of result.matchedChunks) {
        allChunks.push({ chunk, document: result.document });
      }
    }

    // Sort by score descending
    allChunks.sort((a, b) => b.chunk.score - a.chunk.score);

    // Apply the threshold. A near-miss (best score within the margin below the
    // threshold) answers from the top few chunks marked low-confidence; anything
    // worse returns zero citations so the refusal path fires. Feeding arbitrary
    // low-relevance chunks to the model produced confident answers from the
    // wrong documents.
    let selected = allChunks.filter((c) => c.chunk.score >= minScore);
    let lowConfidence = false;
    if (selected.length === 0 && allChunks.length > 0) {
      const bestScore = allChunks[0]!.chunk.score;
      if (bestScore >= minScore - LOW_CONFIDENCE_MARGIN) {
        this.logger.warn(
          `All ${allChunks.length} chunks scored below ANSWER_MIN_CHUNK_SCORE=${minScore}; ` +
            `best=${bestScore.toFixed(3)} is a near miss — answering low-confidence from top ${LOW_CONFIDENCE_TOP_N}.`,
        );
        // Every fallback chunk must itself be within the near-miss margin —
        // otherwise scores like 0.35/0.05/0.01 would feed two unrelated excerpts
        // to the model, recreating the confident-wrong-document behavior.
        selected = allChunks
          .filter((c) => c.chunk.score >= minScore - LOW_CONFIDENCE_MARGIN)
          .slice(0, LOW_CONFIDENCE_TOP_N);
        lowConfidence = true;
      } else {
        this.logger.warn(
          `All ${allChunks.length} chunks scored below ANSWER_MIN_CHUNK_SCORE=${minScore} ` +
            `(best: ${bestScore.toFixed(3)}) — refusing instead of answering from irrelevant chunks.`,
        );
        return { prompt: "", citations: [], lowConfidence: false };
      }
    }

    // Dedupe up front so excerpt numbers in the prompt and citation indices stay
    // aligned: [n] in the model's answer resolves to citations[index === n] exactly.
    const deduped = selected.filter(
      (entry, position, all) =>
        position ===
        all.findIndex(
          (candidate) =>
            candidate.document.id === entry.document.id &&
            candidate.chunk.chunkIndex === entry.chunk.chunkIndex,
        ),
    );

    // Build numbered citations and sections grouped by document
    const citations: AnswerCitation[] = [];
    const docSectionsMap = new Map<
      string,
      { title: string; metadataLine: string | null; sections: string[] }
    >();

    deduped.forEach(({ chunk, document }, position) => {
      const excerptIndex = position + 1;
      const pageLabel =
        chunk.pageFrom && chunk.pageTo && chunk.pageFrom !== chunk.pageTo
          ? `Pages ${chunk.pageFrom}-${chunk.pageTo}`
          : chunk.pageFrom
            ? `Page ${chunk.pageFrom}`
            : "Unknown page";

      const headingPrefix = chunk.heading ? `**${chunk.heading}**\n` : "";

      const entry = docSectionsMap.get(document.id) ?? {
        title: document.title,
        metadataLine: buildDocumentMetadataLine(document),
        sections: [],
      };
      entry.sections.push(
        `[Excerpt ${excerptIndex}, ${pageLabel}, Relevance: ${Math.round(chunk.score * 100)}%]\n${headingPrefix}${chunk.text}`,
      );
      docSectionsMap.set(document.id, entry);

      citations.push({
        documentId: document.id,
        documentTitle: document.title,
        chunkIndex: chunk.chunkIndex,
        pageFrom: chunk.pageFrom,
        pageTo: chunk.pageTo,
        quote: chunk.text.replace(/\s+/g, " ").trim().slice(0, 280),
        score: chunk.score,
        index: excerptIndex,
      });
    });

    const sections: string[] = [];
    for (const [, doc] of docSectionsMap) {
      const metadataSuffix = doc.metadataLine ? `\n${doc.metadataLine}` : "";
      sections.push(`### Document: "${doc.title}"${metadataSuffix}\n\n${doc.sections.join("\n\n")}`);
    }

    return {
      prompt: sections.join("\n\n---\n\n"),
      citations,
      lowConfidence,
    };
  }

  private buildMessages(question: string, context: string, responseLanguage?: AppLanguage | null) {
    const targetLanguageInstruction =
      responseLanguage === "de"
        ? "- Answer in German."
        : responseLanguage === "en"
          ? "- Answer in English."
          : "- Answer in the same language as the question (e.g., German question = German answer).";

    return [
      {
        role: "system" as const,
        content: [
          "You are a document archive assistant. Your task is to answer user questions based ONLY on the provided document excerpts.",
          "",
          "Rules:",
          "- Base your answer exclusively on the provided excerpts. Never fabricate information.",
          "- If the excerpts do not contain enough information, clearly state that.",
          "- Cite sources inline with the bracketed excerpt number, e.g. [1] or [2][4]. Every excerpt is labeled with its number.",
          "- Be concise and direct. Avoid unnecessary preamble.",
          targetLanguageInstruction,
          "- When multiple documents corroborate the same fact, mention the agreement.",
          "- If amounts, dates, or key terms are present, include them precisely.",
        ].join("\n"),
      },
      {
        role: "user" as const,
        content: `## Document Excerpts\n\n${context}\n\n---\n\n## Question\n${question}`,
      },
    ];
  }
}

/**
 * Chunk embeddings carry a contextual prefix (document title, correspondent) at
 * embed time, but the retrieved chunk text does not. This metadata line closes
 * that train/serve gap cheaply without re-embedding anything.
 */
function buildDocumentMetadataLine(document: SemanticSearchResult["document"]): string | null {
  const parts: string[] = [];
  if (document.correspondent?.name) {
    parts.push(`Correspondent: ${document.correspondent.name}`);
  }
  if (document.documentType?.name) {
    parts.push(`Type: ${document.documentType.name}`);
  }
  if (document.issueDate) {
    parts.push(`Issue date: ${document.issueDate}`);
  }

  return parts.length > 0 ? `[${parts.join(" | ")}]` : null;
}
