import { Injectable, Logger } from "@nestjs/common";
import type {
  AppLanguage,
  AnswerCitation,
  AnswerQueryResponse,
  SemanticSearchResult,
} from "@openkeep/types";

import type { AnswerProvider } from "./provider.types";
import { ExtractiveAnswerProvider } from "./extractive-answer.provider";
import { LlmService, type LlmStreamChunk } from "./llm.service";

@Injectable()
export class LlmAnswerProvider implements AnswerProvider {
  private readonly logger = new Logger(LlmAnswerProvider.name);

  constructor(
    private readonly llmService: LlmService,
    private readonly extractiveProvider: ExtractiveAnswerProvider,
  ) {}

  async answer(input: {
    question: string;
    results: SemanticSearchResult[];
    maxCitations: number;
    responseLanguage?: AppLanguage | null;
  }): Promise<{
    status: AnswerQueryResponse["status"];
    answer: string | null;
    reasoning: string | null;
    citations: AnswerCitation[];
  }> {
    if (!this.llmService.isConfigured()) {
      return this.extractiveProvider.answer(input);
    }

    const context = this.buildContext(input.results);

    if (context.citations.length === 0) {
      this.logger.warn("No chunks passed score threshold — all results filtered out");
      return {
        status: "insufficient_evidence",
        answer: null,
        reasoning: "No document chunks with sufficient relevance were found.",
        citations: [],
      };
    }

    const messages = this.buildMessages(input.question, context.prompt, input.responseLanguage);
    const answer = await this.llmService.complete({
      messages,
      temperature: 0.1,
      maxTokens: 1024,
    });

    if (!answer) {
      this.logger.warn("LLM completion returned null, falling back to extractive");
      return this.extractiveProvider.answer(input);
    }

    return {
      status: "answered",
      answer: answer.trim(),
      reasoning: `Generated by ${this.llmService.getProviderInfo()?.provider ?? "LLM"} based on ${context.citations.length} grounded excerpt(s).`,
      citations: context.citations.slice(0, input.maxCitations),
    };
  }

  async *streamAnswer(input: {
    question: string;
    results: SemanticSearchResult[];
    maxCitations: number;
    responseLanguage?: AppLanguage | null;
  }): AsyncGenerator<LlmStreamChunk & { citations?: AnswerCitation[] }> {
    if (!this.llmService.isConfigured()) {
      const result = await this.extractiveProvider.answer(input);
      yield { text: result.answer ?? "Insufficient evidence to answer this question.", done: false };
      yield { text: "", done: true, citations: result.citations };
      return;
    }

    const context = this.buildContext(input.results);

    if (context.citations.length === 0) {
      this.logger.warn("No chunks passed score threshold for streaming — all results filtered out");
      yield { text: "I couldn't find sufficient evidence in your documents to answer this question.", done: false };
      yield { text: "", done: true, citations: [] };
      return;
    }

    const messages = this.buildMessages(input.question, context.prompt, input.responseLanguage);

    const stream = this.llmService.stream({
      messages,
      temperature: 0.1,
      maxTokens: 1024,
    });

    for await (const chunk of stream) {
      if (chunk.done) {
        yield { text: "", done: true, citations: context.citations.slice(0, input.maxCitations) };
        return;
      }

      yield { text: chunk.text, done: false };
    }

    yield { text: "", done: true, citations: context.citations.slice(0, input.maxCitations) };
  }

  // ---------------------------------------------------------------------------
  // Internals
  // ---------------------------------------------------------------------------

  private buildContext(results: SemanticSearchResult[]): {
    prompt: string;
    citations: AnswerCitation[];
  } {
    const MIN_SCORE = 0.25;
    const FALLBACK_TOP_N = 6;

    // Collect all chunks across all results with their parent document info
    const allChunks: Array<{
      chunk: SemanticSearchResult["matchedChunks"][number];
      document: SemanticSearchResult["document"];
    }> = [];

    for (const result of results) {
      for (const chunk of result.matchedChunks) {
        allChunks.push({ chunk, document: result.document });
      }
    }

    // Sort by score descending
    allChunks.sort((a, b) => b.chunk.score - a.chunk.score);

    // Apply threshold, but if nothing passes, take the top N as fallback
    let selected = allChunks.filter((c) => c.chunk.score >= MIN_SCORE);
    if (selected.length === 0 && allChunks.length > 0) {
      this.logger.warn(
        `All ${allChunks.length} chunks scored below MIN_SCORE=${MIN_SCORE}. ` +
          `Taking top ${FALLBACK_TOP_N} by score (best: ${allChunks[0]?.chunk.score.toFixed(3)}).`,
      );
      selected = allChunks.slice(0, FALLBACK_TOP_N);
    }

    // Build citations and sections grouped by document
    const citations: AnswerCitation[] = [];
    const docSectionsMap = new Map<string, { title: string; sections: string[] }>();

    for (const { chunk, document } of selected) {
      const pageLabel =
        chunk.pageFrom && chunk.pageTo && chunk.pageFrom !== chunk.pageTo
          ? `Pages ${chunk.pageFrom}-${chunk.pageTo}`
          : chunk.pageFrom
            ? `Page ${chunk.pageFrom}`
            : "Unknown page";

      const headingPrefix = chunk.heading ? `**${chunk.heading}**\n` : "";

      const entry = docSectionsMap.get(document.id) ?? { title: document.title, sections: [] };
      entry.sections.push(
        `[Chunk ${chunk.chunkIndex}, ${pageLabel}, Relevance: ${Math.round(chunk.score * 100)}%]\n${headingPrefix}${chunk.text}`,
      );
      docSectionsMap.set(document.id, entry);

      citations.push({
        documentId: document.id,
        documentTitle: document.title,
        chunkIndex: chunk.chunkIndex,
        pageFrom: chunk.pageFrom,
        pageTo: chunk.pageTo,
        quote: chunk.text.replace(/\s+/g, " ").trim().slice(0, 280),
        score: chunk.score,
      });
    }

    const sections: string[] = [];
    for (const [, doc] of docSectionsMap) {
      sections.push(`### Document: "${doc.title}"\n\n${doc.sections.join("\n\n")}`);
    }

    return {
      prompt: sections.join("\n\n---\n\n"),
      citations: citations
        .sort((a, b) => b.score - a.score)
        .filter(
          (citation, index, all) =>
            index === all.findIndex((c) => c.documentId === citation.documentId && c.chunkIndex === citation.chunkIndex),
        ),
    };
  }

  private buildMessages(question: string, context: string, responseLanguage?: AppLanguage | null) {
    const targetLanguageInstruction =
      responseLanguage === "de"
        ? "- Answer in German."
        : responseLanguage === "en"
          ? "- Answer in English."
          : "- Answer in the same language as the question (e.g., German question = German answer).";

    return [
      {
        role: "system" as const,
        content: [
          "You are a document archive assistant. Your task is to answer user questions based ONLY on the provided document excerpts.",
          "",
          "Rules:",
          "- Base your answer exclusively on the provided excerpts. Never fabricate information.",
          "- If the excerpts do not contain enough information, clearly state that.",
          '- Cite sources inline using the format [Document: "Title", Page: N] when referencing specific information.',
          "- Be concise and direct. Avoid unnecessary preamble.",
          targetLanguageInstruction,
          "- When multiple documents corroborate the same fact, mention the agreement.",
          "- If amounts, dates, or key terms are present, include them precisely.",
        ].join("\n"),
      },
      {
        role: "user" as const,
        content: `## Document Excerpts\n\n${context}\n\n---\n\n## Question\n${question}`,
      },
    ];
  }
}
