#!/usr/bin/env node
/**
 * Generates `apps/web/src/tokens.css` from `packages/tokens` (#124).
 *
 * CSS cannot import a TS module, so the web client's `--ok-*` custom properties
 * are generated. Run with `--check` to fail when the checked-in file is stale;
 * that is what CI does.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "../..");
const OUT = resolve(root, "apps/web/src/tokens.css");

/** The package is plain data, so it is cheaper to read than to build first. */
function readPalettes() {
  const source = readFileSync(resolve(root, "packages/tokens/src/index.ts"), "utf8");
  const palettes = {};
  for (const name of ["light", "dark"]) {
    const start = source.indexOf(`const ${name}`);
    const end = source.indexOf("\n};", start);
    const body = source.slice(start, end);
    const entries = {};
    for (const [, key, value] of body.matchAll(/\n  ([a-zA-Z]+): "([^"]+)"/g)) {
      entries[key] = value;
    }
    const ramp = [...body.matchAll(/\n    "(#[0-9a-fA-F]{6})"/g)].map((m) => m[1]);
    palettes[name] = { entries, ramp };
  }
  return palettes;
}

/** `borderSoft` → `--ok-border-soft` */
function cssName(key) {
  return `--ok-${key.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`)}`;
}

function block(selector, scheme, { entries, ramp }) {
  const lines = [`${selector} {`, `  color-scheme: ${scheme};`, ""];
  for (const [key, value] of Object.entries(entries)) {
    lines.push(`  ${cssName(key)}: ${value};`);
  }
  lines.push("");
  ramp.forEach((value, index) => lines.push(`  --ok-cat-${index + 1}: ${value};`));
  lines.push("}");
  return lines.join("\n");
}

const palettes = readPalettes();
const generated = [
  "/* Generated by scripts/tokens/generate.mjs from packages/tokens. Do not edit. */",
  "",
  block(":root", "light", palettes.light),
  "",
  block('[data-theme="dark"]', "dark", palettes.dark),
  "",
].join("\n");

if (process.argv.includes("--check")) {
  const current = readFileSync(OUT, "utf8");
  if (current !== generated) {
    console.error(
      "apps/web/src/tokens.css is stale. Run `node scripts/tokens/generate.mjs`.",
    );
    process.exit(1);
  }
  console.log("tokens.css is up to date with packages/tokens");
} else {
  writeFileSync(OUT, generated);
  console.log(`wrote ${OUT}`);
}
