/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as TaxesRouteImport } from './routes/taxes'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SettingsRouteRouteImport } from './routes/settings/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as DocumentsIndexRouteImport } from './routes/documents/index'
import { Route as SettingsTaxonomyRouteImport } from './routes/settings/taxonomy'
import { Route as SettingsProvidersRouteImport } from './routes/settings/providers'
import { Route as DocumentsDocumentIdRouteImport } from './routes/documents/$documentId'
import { Route as CorrespondentsSlugRouteImport } from './routes/correspondents/$slug'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const TaxesRoute = TaxesRouteImport.update({
  id: '/taxes',
  path: '/taxes',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const DocumentsIndexRoute = DocumentsIndexRouteImport.update({
  id: '/documents/',
  path: '/documents/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsTaxonomyRoute = SettingsTaxonomyRouteImport.update({
  id: '/taxonomy',
  path: '/taxonomy',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsProvidersRoute = SettingsProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const DocumentsDocumentIdRoute = DocumentsDocumentIdRouteImport.update({
  id: '/documents/$documentId',
  path: '/documents/$documentId',
  getParentRoute: () => rootRouteImport,
} as any)
const CorrespondentsSlugRoute = CorrespondentsSlugRouteImport.update({
  id: '/correspondents/$slug',
  path: '/correspondents/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/review': typeof ReviewRoute
  '/search': typeof SearchRoute
  '/setup': typeof SetupRoute
  '/taxes': typeof TaxesRoute
  '/upload': typeof UploadRoute
  '/correspondents/$slug': typeof CorrespondentsSlugRoute
  '/documents/$documentId': typeof DocumentsDocumentIdRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/settings/taxonomy': typeof SettingsTaxonomyRoute
  '/documents/': typeof DocumentsIndexRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/review': typeof ReviewRoute
  '/search': typeof SearchRoute
  '/setup': typeof SetupRoute
  '/taxes': typeof TaxesRoute
  '/upload': typeof UploadRoute
  '/correspondents/$slug': typeof CorrespondentsSlugRoute
  '/documents/$documentId': typeof DocumentsDocumentIdRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/settings/taxonomy': typeof SettingsTaxonomyRoute
  '/documents': typeof DocumentsIndexRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/review': typeof ReviewRoute
  '/search': typeof SearchRoute
  '/setup': typeof SetupRoute
  '/taxes': typeof TaxesRoute
  '/upload': typeof UploadRoute
  '/correspondents/$slug': typeof CorrespondentsSlugRoute
  '/documents/$documentId': typeof DocumentsDocumentIdRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/settings/taxonomy': typeof SettingsTaxonomyRoute
  '/documents/': typeof DocumentsIndexRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/login'
    | '/profile'
    | '/review'
    | '/search'
    | '/setup'
    | '/taxes'
    | '/upload'
    | '/correspondents/$slug'
    | '/documents/$documentId'
    | '/settings/providers'
    | '/settings/taxonomy'
    | '/documents/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/profile'
    | '/review'
    | '/search'
    | '/setup'
    | '/taxes'
    | '/upload'
    | '/correspondents/$slug'
    | '/documents/$documentId'
    | '/settings/providers'
    | '/settings/taxonomy'
    | '/documents'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/login'
    | '/profile'
    | '/review'
    | '/search'
    | '/setup'
    | '/taxes'
    | '/upload'
    | '/correspondents/$slug'
    | '/documents/$documentId'
    | '/settings/providers'
    | '/settings/taxonomy'
    | '/documents/'
    | '/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  ReviewRoute: typeof ReviewRoute
  SearchRoute: typeof SearchRoute
  SetupRoute: typeof SetupRoute
  TaxesRoute: typeof TaxesRoute
  UploadRoute: typeof UploadRoute
  CorrespondentsSlugRoute: typeof CorrespondentsSlugRoute
  DocumentsDocumentIdRoute: typeof DocumentsDocumentIdRoute
  DocumentsIndexRoute: typeof DocumentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taxes': {
      id: '/taxes'
      path: '/taxes'
      fullPath: '/taxes'
      preLoaderRoute: typeof TaxesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/documents/': {
      id: '/documents/'
      path: '/documents'
      fullPath: '/documents/'
      preLoaderRoute: typeof DocumentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/taxonomy': {
      id: '/settings/taxonomy'
      path: '/taxonomy'
      fullPath: '/settings/taxonomy'
      preLoaderRoute: typeof SettingsTaxonomyRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/providers': {
      id: '/settings/providers'
      path: '/providers'
      fullPath: '/settings/providers'
      preLoaderRoute: typeof SettingsProvidersRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/documents/$documentId': {
      id: '/documents/$documentId'
      path: '/documents/$documentId'
      fullPath: '/documents/$documentId'
      preLoaderRoute: typeof DocumentsDocumentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/correspondents/$slug': {
      id: '/correspondents/$slug'
      path: '/correspondents/$slug'
      fullPath: '/correspondents/$slug'
      preLoaderRoute: typeof CorrespondentsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SettingsRouteRouteChildren {
  SettingsProvidersRoute: typeof SettingsProvidersRoute
  SettingsTaxonomyRoute: typeof SettingsTaxonomyRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsProvidersRoute: SettingsProvidersRoute,
  SettingsTaxonomyRoute: SettingsTaxonomyRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  ReviewRoute: ReviewRoute,
  SearchRoute: SearchRoute,
  SetupRoute: SetupRoute,
  TaxesRoute: TaxesRoute,
  UploadRoute: UploadRoute,
  CorrespondentsSlugRoute: CorrespondentsSlugRoute,
  DocumentsDocumentIdRoute: DocumentsDocumentIdRoute,
  DocumentsIndexRoute: DocumentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
